set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on # relay focus events (e.g. window change) to programs

##################
# Terminal Stuff #
##################

# TODO: Pasting using Ctrl+Shift+v in nvim with this on doesn't work
set extended-keys on

# alacritty
set terminal-overrides "alacritty:Tc" # true colors
set -a terminal-overrides ',alacritty:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colors - needs tmux-3.0 (https://ryantravitz.com/blog/2023-02-18-pull-of-the-undercurl/)

############
# Keybinds #
############

# rebind prefix
set -g prefix C-a
bind C-a send-prefix

bind -n M-x copy-mode

# pane navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -n M-q kill-pane

# window navigation
bind -n M-1 select-window -t :=1
bind -n M-2 select-window -t :=2
bind -n M-3 select-window -t :=3
bind -n M-4 select-window -t :=4
bind -n M-5 select-window -t :=5
bind -n M-6 select-window -t :=6
bind -n M-7 select-window -t :=7
bind -n M-8 select-window -t :=8
bind -n M-9 select-window -t :=9
bind -n M-0 select-window -t :=0

bind -n M-H split-window -hbc '#{pane_current_path}'
bind -n M-J split-window -vc '#{pane_current_path}'
bind -n M-K split-window -vbc '#{pane_current_path}'
bind -n M-L split-window -hc '#{pane_current_path}'

bind -n M-Enter new-window -c '#{pane_current_path}'

bind -n M-Q kill-window
bind M-q kill-session
bind M-Q kill-server

bind -n M-d detach

bind M-r source ~/.tmux.conf

##############
# Appearance #
##############

# colors
set -g @accent brightyellow
set -g @primary brightcyan
set -g @border brightblack

# panes
set -g pane-border-status top
set -g pane-border-indicators arrows
set -g pane-border-format "#[bold][#T]"
set -g pane-border-lines heavy
set -g pane-border-style "fg=#{@border}"
set -g pane-active-border-style "fg=#{@primary}"

# status
set -g status-position top
set -g status-style "fg=#{@border}"
# left status
set -g status-left-length 0
# right status
set -g status-right "#{?client_prefix, #[fg=brightred bold blink]prefix#[default] ,}#{?pane_in_mode, #[fg=brightcyan bold]#{pane_mode}#[default] ,}"
set -g status-right-length 0
# window format
set -g window-status-format "#[fg=yellow][#I]#[default] #W"
set -g window-status-current-format "#[fg=#{@accent} bold][#I] #[fg=brightwhite]#W"
