[".config/git-completion.bash"]
  type = "file"
  url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"

[".config/git-prompt.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
