"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[┌\[ $directory \](─\[ $git_branch( $git_status)( $git_state) \])(─\[ $python \])(─\[ $nix_shell \])$fill(\[ $sudo \]─)\[ ($username$hostname )$shell $time $os\](─\[( $status)( $cmd_duration) \])
└\[ ](bold bright-red)
'''

add_newline = false

##{
# R1 Left Modules
#

[directory]
format = '[$path]($style)'
style = "bright-yellow"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
style = "bright-cyan"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "bold bright-blue"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'

[python]
format = '([$symbol$virtualenv]($style))'
symbol = " "

[nix_shell]
format = '[$symbol$state( \($name\))]($style)'
style = "bold bright-cyan"
symbol = "󱄅 "

##}

[fill]
symbol = "─"
style = "bold bright-red"

##{
# R1 Right Modules
#

[sudo]
format = '[$symbol]($style)'
symbol = ""
style = "blink bold bright-red"
disabled = false

[username]
format = '([$user]($style)[@](bold bright-cyan))'
style_root = "blink bold bright-yellow"

[hostname]
format = '[$hostname]($style)'
style = 'bold bright-blue'

[os]
disabled = false
style = "bold bright-cyan"

[os.symbols]
NixOS = " "
Arch = " "
openSUSE = " "
Windows = " "

[shell]
format = '$indicator'
disabled = false
nu_indicator = "[ü](bold bright-green)"
fish_indicator = "[󰻳](bold bright-blue)"
bash_indicator = "[](bold bright-green)"

[time]
disabled = false
format = "[$time]($style)"
style = "bold bright-purple"

[cmd_duration]
format = '[$duration]($style)'

[status]
disabled = false
format = '[$symbol$status]($style)'
symbol = ''
