abbr -a p "$PACK_MAN"
abbr -a sctl "sudo systemctl"
abbr -a ls "eza --icons always"
abbr -a la "eza --icons -AlHg"
abbr -a lam "eza --icons -AlHg -s modified --time-style long-iso"
abbr -a che "chezmoi"
abbr -a chema "chezmoi merge-all ."
# fzf modified file in current directory and merge it
abbr -a chemf "chezmoi merge (chezmoi --path-style absolute status . | awk '{print \$2}' | fzf)"
abbr -a cherf "chezmoi re-add (chezmoi --path-style absolute status . | awk '{print \$2}' | fzf)"
abbr -a bat "bat --theme gruvbox-dark -f"
abbr -a ip "ip -c=always"
abbr -a snaproot "sudo btrfs subvolume snapshot -r / /.btrfs-snapshots/@_$(date -Iseconds)"
abbr -a subdel "sudo btrfs subvolume delete"
